# Generated by Django 4.2.1 on 2023-10-28 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rgmloans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
                ('payment_frequency', models.CharField(max_length=25)),
                ('rate', models.IntegerField(default=0)),
                ('min_credit', models.IntegerField(default=0)),
                ('min_amount', models.IntegerField(default=0)),
                ('max_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_approved', models.DateTimeField(auto_now_add=True)),
                ('payment_starting_date', models.DateTimeField(auto_now_add=True)),
                ('payment_frequency', models.CharField(max_length=25)),
                ('payment_amount', models.IntegerField(default=0)),
                ('interest_rate', models.IntegerField(default=0)),
                ('num_of_months', models.IntegerField(default=0)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=200)),
                ('loan_type', models.CharField(max_length=200)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Applied'), ('p', 'Pending'), ('g', 'Granted'), ('r', 'Rejected')], default='a', help_text='Loan Application Status', max_length=1)),
                ('loan_applied_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_applied_for', to='rgmloans.loanoffer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
