# Generated by Django 4.2.1 on 2023-10-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgmloans', '0002_loanoffer_loan_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='loan_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='loan_type',
        ),
        migrations.AddField(
            model_name='application',
            name='requested_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanoffer',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
