# Generated by Django 4.2.1 on 2023-11-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgmloans', '0003_remove_application_loan_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='loanoffer',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='loanoffer',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='loanoffer',
            name='min_credit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanoffer',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='annual_family_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='assets_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='existing_loan_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(choices=[('AB', 'AB'), ('BC', 'BC'), ('MB', 'MB'), ('NB', 'NB'), ('NL', 'NL'), ('NS', 'NS'), ('ON', 'ON'), ('PE', 'PE'), ('SK', 'SK'), ('QC', 'QC')], default='AB', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
