# Generated by Django 4.2.1 on 2023-11-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgmloans', '0004_alter_application_requested_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('Applied', 'Applied'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='a', help_text='Loan Application Status', max_length=20),
        ),
    ]
