# Generated by Django 4.2.1 on 2023-11-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgmloans', '0005_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('Applied', 'Applied'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Applied', help_text='Loan Application Status', max_length=20),
        ),
    ]
