# Generated by Django 4.2.1 on 2023-11-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgmloans', '0006_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanoffer',
            name='max_tenure',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
