# Generated by Django 4.2.1 on 2023-11-08 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rgmloans', '0007_loanoffer_max_tenure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='rgmloans.application'),
        ),
    ]
