# Generated by Django 4.2.1 on 2023-11-08 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgmloans', '0008_alter_loan_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='application',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='user',
        ),
    ]
