# Generated by Django 4.2.1 on 2023-11-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgmloans', '0010_loan_amount_approved_loan_application_loan_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('postal_code', models.CharField(blank=True, max_length=6, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_contact', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
