# Generated by Django 4.2.1 on 2023-11-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgmloans', '0011_contactnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactnotification',
            name='message',
            field=models.CharField(blank=True, default='Loan application', max_length=200, null=True),
        ),
    ]
