# Generated by Django 4.2.1 on 2023-11-20 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rgmloans', '0014_alter_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='application',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='rgmloans.application'),
            preserve_default=False,
        ),
    ]
