# Generated by Django 4.2.1 on 2023-11-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgmloans', '0015_alter_loan_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='balance_owing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='payments_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='payments_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
