# Generated by Django 4.2.1 on 2023-11-20 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgmloans', '0016_loan_balance_owing_loan_payments_made_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='payment_ending_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='loan',
            name='payment_starting_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
