# Generated by Django 4.2.1 on 2023-11-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgmloans', '0017_loan_payment_ending_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='no_of_payments',
            field=models.IntegerField(default=0),
        ),
    ]
