# Generated by Django 4.2.1 on 2023-11-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgmloans', '0018_loan_no_of_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='application_status',
            field=models.CharField(blank=True, default='Applied', max_length=20),
        ),
    ]
