# Generated by Django 4.2.1 on 2023-11-21 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgmloans', '0019_loan_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_approved',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='loan',
            name='payment_starting_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
