# Generated by Django 4.2.1 on 2023-11-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgmloans', '0021_alter_user_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(choices=[('AB', 'AB'), ('BC', 'BC'), ('MB', 'MB'), ('NB', 'NB'), ('NL', 'NL'), ('NS', 'NS'), ('ON', 'ON'), ('PE', 'PE'), ('SK', 'SK'), ('QC', 'QC')], default='AB', max_length=2),
        ),
    ]
